### ISSUE TITLE
Documentation on setting up config.properties

### ISSUE THREAD

**Issue by zabackary** [SunkenSplash/VRC-RoboScout-Android#4]
Hi there,

I just discovered that you're been working on an Android version of the great VRC RoboScout app for iOS. Some of my team members have it, and it's *much* better than VEX Via.

I was trying to build this app locally to test some things out using Android Studio Iguana (2023.2.1 patch 2), but the build failed because the API keys for the RobotEvents API aren't included in the repo, for obvious reasons. Since I'm interested in fiddling around with this app and probably contributing back, I was wondering, how should those API keys be set up/obtained? Do I need to create a RobotEvents account then use [this link](https://www.robotevents.com/api/v2/accessRequest/create) to get a token, and is it free? Do you know whether there's a development token available, or is it okay to just use the ones you use?

Thank you in advance, and sorry for bothering you, since I assume you must be busy at Worlds (I am too). I'd love to visit your team though :)

**Comment by SprintKeyz** [comment]
Here's how you set it up:

1. Grab a robotevents API key from https://www.robotevents.com/api/v2/tokens. Name it whatever, something like `RS_API_KEY`
2. Create a file called `config.properties` in the root of the project
3. Put the following in the file: `ROBOTEVENTS_API_KEY="YOUR_ROBOTEVENTS_API_KEY_HERE"`
4. Rebuild and you should be good to go!

**Comment by zabackary** [comment]
Thanks so much! I'll try again tonight.

**Comment by zabackary** [comment]
Apologies for leaving this open. Thank you for the help.
